name: Service quality CI
on: [push]
jobs:
#  do-it:
#    runs-on: ubuntu-latest    
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          path: app
#      - run: ls -als
#      - run: ls -als app/
#      - run: docker build -t projectpoc:test .
#        working-directory: app/ProjectPoc
#      - run: scripts/Itest.sh
#        working-directory: app/IntegrationTest
#      - name: Publishing Test Report & logs
#        uses: actions/upload-artifact@v2
#        with:
#          name: reporting
#          path: app/IntegrationTest/reporting
  test:
    uses: mauroarias/custom-action/.github/workflows/share-qa-workflow.yml@main
    with:
      service_name: ProjectPoc
      dockerfile_path: ProjectPoc
      itest_path: IntegrationTest