name: Service quality CI
on: [push]
jobs:
  build-docker:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v3
        with:
          path: app
      - run: cd app/ProjectPoc
      - run: ls -als
      - run: docker build -f Dockerfile -t projectpoc:test .
      - run: cd ../IntegrationTest
      - run: scripts/Itest.sh