name: Service quality CI
on: [push]
jobs:
  build-docker:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v3
        with:
          path: app
      - run: docker build -t projectpoc:test .
        working-directory: app/ProjectPoc
      - run: scripts/Itest.sh
        working-directory: app/IntegrationTest
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: "app/IntegrationTest/reporting/*.html"
      - name: Publish logs
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: "app/IntegrationTest/reporting/*.log"